ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'ADMIN_CUSTOMER_ACCOUNT_REQUESTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'ADMIN_COMMERCE_QUOTE_REQUESTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'ADMIN_COMMERCE_ORDER_REQUESTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'ADMIN_PRODUCT_IMAGE_PIPELINE_ALERT';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_EMAIL_VERIFICATION';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_ACCOUNT_APPROVED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_ACCOUNT_REJECTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_ACCOUNT_SUSPENDED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_QUOTE_REQUESTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_ORDER_REQUESTED';
ALTER TYPE "EmailNotificationKind" ADD VALUE IF NOT EXISTS 'CUSTOMER_ORDER_STATUS';

ALTER TYPE "CustomerEmailDeliveryStatus" ADD VALUE IF NOT EXISTS 'QUEUED';

CREATE TABLE "RequestRateLimit" (
  "keyHash" CHAR(64) NOT NULL,
  "windowStart" TIMESTAMP(3) NOT NULL,
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "RequestRateLimit_pkey" PRIMARY KEY ("keyHash")
);

CREATE INDEX "RequestRateLimit_windowStart_idx" ON "RequestRateLimit"("windowStart");
