-- PROPOSAL_STUDIO_PREVIEW audit-only events. No proposal, revision, snapshot
-- or commercial fields are changed by Hito F preview interactions.
ALTER TYPE "ProposalEventType" ADD VALUE IF NOT EXISTS 'PROPOSAL_PREVIEW_OPENED';
ALTER TYPE "ProposalEventType" ADD VALUE IF NOT EXISTS 'PROPOSAL_PREVIEW_THEME_CHANGED';
ALTER TYPE "ProposalEventType" ADD VALUE IF NOT EXISTS 'PROPOSAL_PREVIEW_DEVICE_CHANGED';
ALTER TYPE "ProposalEventType" ADD VALUE IF NOT EXISTS 'PROPOSAL_PREVIEW_VALIDATED';
ALTER TYPE "ProposalEventType" ADD VALUE IF NOT EXISTS 'PROPOSAL_PRESENTATION_MODE_OPENED';
