type CompleteDraftTemplateInput = {
  clientName: string;
  companyName?: string | null;
  context: string;
  title: string;
};

function inline(value: string) {
  return value.replace(/\s+/gu, " ").trim();
}

/**
 * A complete, safe starting document for a new Proposal DRAFT. It deliberately
 * references private `asset:` aliases rather than public URLs: the renderer
 * shows a useful placeholder until the admin uploads the matching asset.
 */
export function createCompleteProposalDraftTemplate({
  clientName,
  companyName,
  context,
  title
}: CompleteDraftTemplateInput) {
  const recipient = inline(companyName || clientName);
  const projectTitle = inline(title);
  const initialContext = inline(context);

  return [
    "---",
    "language: es",
    "subtitle: Plantilla editorial completa para revisar cada bloque disponible.",
    "tags:",
    "  - proposal-draft",
    "  - janvier",
    "template: janvier-complete-draft",
    "theme: night",
    "---",
    "",
    `# ${projectTitle}`,
    "",
    `Preparado para **${recipient}**. Esta es una plantilla de trabajo: reemplaza el texto de muestra antes de compartirla.`,
    "",
    "## Resumen ejecutivo {#executive-summary type=EXECUTIVE_SUMMARY}",
    "",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Esta propuesta convierte una necesidad operativa en una ruta verificable.",
    "",
    ":::janvier-callout",
    "type: signal",
    "title: Punto de decisión",
    "",
    "Define qué debe estar aprobado antes de iniciar la siguiente fase.",
    ":::",
    "",
    "## Contexto {#context type=CONTEXT}",
    "",
    initialContext,
    "",
    "> Esta cita sirve para destacar una restricción, una evidencia o una frase del cliente.",
    "",
    "## Objetivos {#objectives type=OBJECTIVES}",
    "",
    "- [x] Comprender el sistema actual.",
    "- [ ] Validar el alcance con las personas responsables.",
    "- [ ] Medir el resultado después de la entrega.",
    "",
    "## Solución propuesta {#solution type=SOLUTION}",
    "",
    "Combina texto **fuerte**, _énfasis_, ~~contenido descartado~~, `código inline` y [un enlace seguro](/contacto).",
    "",
    "```ts",
    "const outcome = 'reemplaza este ejemplo por una regla o interfaz real';",
    "```",
    "",
    "## Arquitectura visual {#architecture type=ARCHITECTURE}",
    "",
    "![Diagrama de arquitectura](asset:architecture-diagram \"Sube un PNG, JPEG, WebP o SVG sanitizado con este alias\")",
    "",
    ":::janvier-metrics",
    "",
    "label: Tiempo actual",
    "value: 12 dias",
    "",
    "label: Meta inicial",
    "value: 4 dias",
    "",
    "label: Riesgo",
    "value: Medio",
    ":::",
    "",
    "## Alcance y entregables {#scope type=SCOPE}",
    "",
    "| Entregable | Evidencia | Estado |",
    "| --- | --- | --- |",
    "| Diagnóstico | Mapa de operación | Por validar |",
    "| Prototipo | Flujo navegable | Planeado |",
    "| Transferencia | Sesión de cierre | Planeado |",
    "",
    ":::janvier-ascii",
    "SYSTEM_READY = 0",
    "INPUT: DISCOVERY",
    "OUTPUT: VERIFIED_SCOPE",
    ":::",
    "",
    "## Alternativas {#alternatives type=ALTERNATIVES}",
    "",
    "{{proposal.options}}",
    "",
    "## Cronograma {#timeline type=TIMELINE}",
    "",
    "{{proposal.timeline}}",
    "",
    "{{proposal.paymentSchedule}}",
    "",
    ":::janvier-page-break",
    ":::",
    "",
    "## Inversión {#investment type=INVESTMENT}",
    "",
    "{{proposal.lineItems}}",
    "",
    "{{proposal.totals}}",
    "",
    "## Condiciones {#conditions type=CONDITIONS}",
    "",
    "- Vigencia: {{proposal.validUntil}}.",
    "- Moneda: {{proposal.currency}}.",
    "- Añade aquí condiciones, supuestos y exclusiones comerciales.",
    "",
    "## Preguntas frecuentes {#faq type=FAQ}",
    "",
    "### ¿Qué necesitamos del cliente?",
    "",
    "Un contacto responsable, acceso a la información relevante y retroalimentación dentro del ciclo acordado.",
    "",
    "### ¿Qué ocurre si cambia el alcance?",
    "",
    "Se documenta el ajuste y se prepara una nueva revisión antes de compartirla.",
    "",
    "## Siguiente paso {#next-steps type=NEXT_STEPS}",
    "",
    ":::janvier-decision",
    "title: Confirmar ruta de trabajo",
    "",
    "Indica si esta propuesta puede avanzar, requiere ajustes o debe archivarse.",
    ":::",
    "",
    "## Notas internas {#internal-notes type=REFERENCE internal=true}",
    "",
    ":::janvier-internal",
    "",
    "Este espacio sólo se muestra en administración. Úsalo para contexto privado, no para información que el cliente deba aceptar.",
    ":::",
    ""
  ].join("\n");
}
